thesis_grading/user/routes.py
from flask import Blueprint, render_template

user = Blueprint("user", __name__, url_prefix="/user")

@user.route("/login")
def login():
    # redir to grading if logged in
    return render_template("user/login.html")

@user.route("/read")
def read():
    #id
    #username
    #password
    #email

    users = [
        {
            "id" : "1",
            "username" : "mahabangmahabangmahabangusername",
            "password" : "123123123123123123123123123123123213",
            "email" : "ju@nd3lacruz_averyverylongemailaddresssss@email.com"
        },
        {
            "id" : "1",
            "username" : "ju@nd3lacruz",
            "password" : "123",
            "email" : "ju@nd3lacruz@email.com"
        },
        {
            "id" : "1",
            "username" : "ju@nd3lacruz",
            "password" : "123",
            "email" : "ju@nd3lacruz@email.com"
        },
        {
            "id" : "1",
            "username" : "ju@nd3lacruz",
            "password" : "123",
            "email" : "ju@nd3lacruz@email.com"
        },
        {
            "id" : "1",
            "username" : "ju@nd3lacruz",
            "password" : "123",
            "email" : "ju@nd3lacruz@email.com"
        }

    ]

    return render_template("user/read.html", users=users)

thesis_grading/templates/user/feed.html
{# thesis_grading/templates/user/feed.html #}

{% extends "user/layout.html" %}
{% block title %} Thesis Feed {% endblock %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='user/css/login.css') }}">
{% endblock %}
{% block content %}
    <div id="login-form" class="card mx-auto mt-5">
        <div class="card-body px-4">
            <div class="card-title text-center h3 mt-3 mb-5">Thesis Evaluation (SIGN-IN TEST)</div>


            <!-- <div id="g_id_onload"
                 data-client_id="100545826118-d773545e36qme94g9pdegrnvbbpdto25.apps.googleusercontent.com"
                 data-context="signin"
                 data-ux_mode="popup"
                 data-callback="onSignIn">
            </div>

            <div class="g_id_signin"
                 data-type="standard"
                 data-shape="pill"
                 data-theme="outline"
                 data-text="signin_with"
                 data-size="large"
                 data-logo_alignment="left">
            </div> -->
            
            <p>Signed in as <span id="username" class="fw-bold"></span><br> with email <span id="email" class="fw-bold"></span></p><br>

            <h5>Feast your eyes with the thesis files:</h4>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deserunt quod eaque accusamus eius maiores atque vitae rerum libero ab sunt aspernatur iusto sapiente, impedit porro dolor pariatur corrupti harum. Assumenda?</p><br>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deserunt quod eaque accusamus eius maiores atque vitae rerum libero ab sunt aspernatur iusto sapiente, impedit porro dolor pariatur corrupti harum. Assumenda?</p><br>


            <div class="d-grid">
                <div class="g-signin2 d-none mb-4 mx-auto"></div>
                <a href="#" onclick="signOut();">Sign out</a>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    {% include 'user/includes/scripts.html' %}
    <script>
        let params = new URLSearchParams(location.search);
        document.querySelector("#username").innerHTML = params.get('name');
        document.querySelector("#email").innerHTML = params.get('email');
    </script>
{% endblock %}

 

thesis_grading/templates/user/layout.html
<!DOCTYPE html>
<html>
<head>
    {% block head %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap, CSS only -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/bootstrap-icons.css') }}">

    <title>{% block title %}{% endblock %}</title>
    {% endblock %}
</head>
<body class="bg-uered">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-0">
                {% block sidebar %}{% endblock %}
            </div>
            <div class="col-md-12">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
    <script src="{{ url_for('static', filename='bootstrap/bootstrap.bundle.min.js') }}"></script>
</body>
</html> 

thesis_grading/templates/user/login.html
{# thesis_grading/templates/user/login.html #}

<!-- 
    username maxlength 11
    both fields required

    responsive on all breakpoints

    ideas: 
    1 add option to continue/ sign in with google 
 -->
{% extends "user/layout.html" %}
{% block title %} Login {% endblock %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='user/css/login.css') }}">
{% endblock %}
{% block content %}
    <div id="login-form" class="card mx-auto mt-5">
        <div class="card-body px-4">
            <div class="card-title text-center h3 mt-3 mb-5">Thesis Evaluation</div>

            <!-- TODO: form attr -->
            <form id="login" action="" method="">

                <div class="form-group">
                    <input type="text" id="username" name="username" class="form-control mb-3" placeholder="Username" maxlength="11" tabindex="1" required>
                    <input type="password" id="password" name="password" class="form-control mb-3" placeholder="Password" tabindex="2" required>

                    <div class="spacer"></div>
                    <a href="{{ url_for('user.reset') }}" class="card-link text-uered" tabindex="4">Forgot password?</a>
                    <button type="submit" class="card-link button btn btn-primary float-end px-4 py-1 mb-4" tabindex="3" disabled>Login</button>

                    <div class="spacer"></div>
                    <div class="divider mb-4">
                        <strong class="divider-title ng-binding text-uppercase fw-bold px-4">or</strong>
                    </div>
                    <div class="d-grid">
                        <div class="g-signin2 mb-4 mx-auto" data-onsuccess="onSignIn"></div>
                        <!-- <div id="g_id_onload"
                             data-client_id="100545826118-d773545e36qme94g9pdegrnvbbpdto25.apps.googleusercontent.com"
                             data-context="signin"
                             data-ux_mode="popup"
                             data-callback="onSignIn">
                        </div>

                        <div class="g_id_signin"
                             data-type="standard"
                             data-shape="pill"
                             data-theme="outline"
                             data-text="signin_with"
                             data-size="large"
                             data-logo_alignment="left">
                        </div> -->
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    {% include 'user/includes/scripts.html' %}
{% endblock %}

 

thesis_grading/templates/user/password_reset.html
{# thesis_grading/templates/user/password_reset.html #}

{% extends "user/layout.html" %}
{% block title %} Login {% endblock %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='user/css/login.css') }}">
{% endblock %}
{% block content %}
    <div id="login-form" class="card mx-auto mt-5">
        <div class="card-body px-4">
            <div class="spacer"></div>
            <div class="card-title text-center h5 mt-3 mb-4">Trouble Logging In?</div>
            <div class="card-subtitle text-muted text-center mb-5">Enter your email or username and we'll send you a link to access your account</div>

            <!-- TODO: form attr -->
            <form id="password_reset" action="" method="">
                <div class="form-group">
                    <!-- TODO: maxlength -->
                    <input type="text" id="username" name="username" class="form-control mb-3" placeholder="Email or Username" maxlength="35" required>
                    <div class="d-grid">
                        <button type="submit" class="btn btn-primary mb-4" disabled="True">Send Login Link</button>
                    </div>
                </div>
            </form>
        </div>
        <a href="{{ url_for('user.login') }}" class="text-center text-uered">
            <div class="card-footer">
                Back to Login
            </div>
        </a>
    </div>
{% endblock %}
{% block scripts %}
    {% include 'user/includes/scripts.html' %}
{% endblock %}
 

thesis_grading/templates/user/read.html
<!-- {{users}} -->



{% extends "user/layout.html" %}


{% block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/user-read.css') }}">
{% endblock %}
{% block title %} All Users {% endblock %}


{% block content %}
    <div class="user-content mt-5 py-5 container bg-white rounded">
        <div class="row justify-content-between">
            <div class="col-3">
                <div class="input-group mb-4">
                    <input class="form-control" type="text" placeholder="Start typing to filter..." required>
                    <button type="submit" class="btn btn-info">Search</button>
                </div>
            </div>
            <div class="col-3 text-end">
                <button class="btn btn-success">Add User<i class="bi bi-plus-lg"></i></button>
            </div>
        </div>

        <div class="user-table">
            <table class="table table-striped is-scrollable">
              <thead>
                <tr>
                  <th class="col-sm-2" scope="col">ID</th>
                  <th class="col-sm-3" scope="col">Username</th>
                  <th scope="col">Password</th>
                  <th class="col-sm-3" scope="col">Email</th>
                </tr>
              </thead>
              <tbody>
                <!-- loop through the dictionaries in users -->
                {% for user in users %}
                <tr>
                    {% for key in user %}
                        {% if key == 'proponents' %}
                            <td class="lh-lg">
                                <!-- loop through values of proponents -->
                                {% for value in user[key] %}
                                    {{ value }}<br>
                                    <!-- for adding comma -->
                                    <!-- {{ "," if user[key].index(value) != user[key]|length - 1 }} --> 
                                {% endfor %}
                            </td>
                        {% else %}
                            <!-- prints value of key if key is not "proponents" -->
                            <td>{{ user[key] }}</td>
                        {% endif %}
                    {% endfor %}
                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>
    </div>
{% endblock %}